config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  get 'guia-de-servicos', to: 'services#index'
  get 'servico/:id/:permalink', to: 'services#show'
  get 'categoria/:category_slug/servicos', to: 'categories#index'
  get 'publico_alvo/:audience_slug/servicos', to: 'audiences#index'

  get 'orgaos', to: 'organs#index'
  get 'orgao/:permalink', to: 'organs#show'

  get 'unidades-de-atendimento', to: 'units#index'
  get 'unidade-de-atendimento/:permalink', to: 'units#show'

  get 'central-de-atendimento', to: 'centers#index'
  get 'central-de-atendimento/:permalink', to: 'centers#show'

  get 'categoria/:permalink', to: 'categories#index'
  get 'publico-alvo/:permalink', to: 'audiences#index'

  get 'arquivos', to: 'home#arquives'
  
  get 'api', to: 'home#api'

  get 'sobre', to: 'home#about'

  namespace :api do
    resources :services, :organs, :units, :centers, :categories, :audiences
    namespace :v1 do
      resources :services, :organs, :units, :centers, :categories, :audiences
    end
  end

  get 'admin', to: redirect('/admin/dashboard')

  namespace :admin do
    resources :services, :organs, :units, :centers, :categories, :audiences, :profiles, :users
    get 'dashboard', to: 'dashboard#index'
    get 'auth_generator', to: 'dashboard#auth_generator'
    post 'organs/uploader', to: 'organs#uploader'
  end

end

app/models/service.rb
class Service
	include Mongoid::Document
	include Mongoid::Search
	include Mongoid::Pagination
	

	field :name, type: String
	field :acronym, type: String
	field :popular_names, type: Array
	field :description, type: String
	field :free, type: Boolean
	field :applicants, type: Array
	field :estimated_time, type: Hash
	field :steps, type: Array
	field :permalink, type: String
	field :other_informations, type: String
	field :active, type: Boolean
	field :highlights, type: Boolean
	field :highlights_value, type: String
	field :date, type: String
	field :date_modified, type: String
	field :maturity_level, type: String
	field :mantener, type: String
	field :coordinator, type: String
	field :latest_updater, type: String

	belongs_to :organ, class_name: "Admin::Organ"
	has_and_belongs_to_many :units, class_name: "Admin::Unit"
	has_and_belongs_to_many :audiences, class_name: "Admin::Audience"
	has_and_belongs_to_many :categories, class_name: "Admin::Category"

	before_save :touch_permalink
	
	
	search_in :name, #:popular_names, categories: :name, organ: :name





	def url
		"#{SITE_URL}/servico/#{id}/#{permalink}"
	end

	def get_keys
		return nil if self.popular_names.blank?

		keys = []

		self.popular_names.collect { |p| keys << p[:name] }

		keys = keys.join(', ')
	end

	private
	
	  def touch_permalink
	    self.permalink = self.name.parameterize
	  end
end		

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
	before_action :set_service, only: [:show, :edit, :update, :destroy]

	before_action :verify_permission

	skip_before_filter :verify_authenticity_token


	def index
		if current_user.admin?
			@services = Service.all		
			#@services = Service.search(params[:search]).order(name).paginate(:per_page => 5, :page => params[:page])

		else
			@services = Service.where(organ_id: current_user.organ_id)
		end
	end

	def new
		inspect
		@service = Service.new
		if current_user
			register_user = File.new("register.txt","a")
			register_user.puts("***********")
			register_user.puts("usuário ",current_user.name)
			register_user.puts("id do perfil ",current_user.profile_id)
			register_user.puts("Seu perfil no sistema",current_user.profile.name)
			register_user.puts("Logado em ", current_user.current_sign_in_at)
			register_user.puts("id do órgão ", current_user.organ_id)
			register_user.puts("Nome do órgão ", current_user.organ.name)
			register_user.puts('Criou serviço id ', @service.id.to_s, "\n")
			register_user.puts("Criou serviço em ", Time.now.strftime("%d/%m/%Y %H:%M"))
			register_user.puts("***********")
			register_user.puts("\n")
			register_user.close()
		end
		@service.latest_updater = current_user.name
	end

	def show
		
	end

	def edit
		@service.date_modified = Time.now.strftime("%d/%m/%Y %H:%M")
		@service.latest_updater = current_user.name
	end

	def create
		@service = Service.new(service_params)
		@service.organ_id = current_user.organ_id if !current_user.admin?
		@service.date = Time.now.strftime("%d/%m/%Y %H:%M")

		respond_to do |format|
			if @service.save
				format.html { redirect_to services_url, notice: 'Serviço criado com sucesso criada com sucesso.' }
				format.json { render :show, status: :created, location: [:admin, @service] }
			else
				format.html { render :new }
				format.json { render json: @service.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		
		@service.date_modified = Time.now.strftime("%d/%m/%Y %H:%M")
		@service.latest_updater = current_user.name
		
		respond_to do |format|
			if @service.update(service_params)
				format.html { redirect_to "/admin/services", notice: 'Serviço atualizado com sucesso.' }
				format.json { render :show, status: :ok, location: [:admin, @service] }
			else
				format.html { render :edit }
				format.json { render json: @services.error, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@service.destroy
		respond_to do |format|
			format.html { redirect_to "/admin/services", notice: 'Serviço excluido com sucesso.' }
			format.json { head :no_content }
		end
	end

	private
	def set_service
		
		@service = Service.find(params[:id])

	end

	def service_params
		params.permit(
						:name,
						:date,
						:date_modified,
						:active,
						:highlights,
						:highlights_value,
						:mantener,
						:coordinator,
						:latest_updater,
						:maturity_level,
						:acronym,
						:description,
						:free,
						:permalink,
						:organ_id,
						:other_informations,
						 estimated_time: [
								:type,
								:unit,
								:min,
								:max,
								:description,
							],
							unit_ids: [],
							audience_ids: [],
							category_ids: [],
							popular_names: [:name],
							applicants: [:type, :requirements],
							steps: [
								:title, :description,
								documents: [:name, cases: [:description]],
								providing_channels: [:type, :description],
								cost: [:description, :coin, :value, :type],
								type_delivery_channel: [:type]
							]
)
	end
end

app/controllers/api/services_controller.rb
class Api::ServicesController < ApiController

	def index
		
		if params[:q] != nil
				@services = Service.full_text_search(params[:q], allow_empty_search: false).where(active: true)
		elsif params[:organ_id]
			@services = Service.where(organ_id: params[:organ_id]).page(params[:page]).per(60)
		
		elsif params[:letter]
			@services = Service.where(name: /^#{params[:letter]}/i).page(params[:page]).per(60)
		
		elsif params[:active]
			@services = Service.where(active: params[:active])

		else
			@services = Service.where(active: true).page(params[:page]).order(name: :asc)
		  #@services = @ordena.per(60)
			#@serall =Service.where(active: true)
		  #@servicess = @ordena.per(60).order(name: :asc)		    
		    
			@total_pages = @services.total_pages
		end
	end

	def show
		@services = Service.find(params[:id])
	end

end

app/controllers/api/v1/services_controller.rb
class	Api::V1::ServicesController < ApplicationController
	def index
		if params[:q]
			@services = Service.full_text_search(params[:q], allow_empty_search: true)
		
		elsif params[:organ_id]
			@services = Service.where(organ_id: params[:organ_id])
		
		elsif params[:letter]
			@services = Service.where(name: /^#{params[:letter]}/i)
		
		elsif params[:active]
			@services = Service.where(active: params[:active])

		else
			@services = Service.order(name: :asc)			
		end	
		
	end

	def show
		@service = Service.find(params[:id])
	end
end

app/controllers/services_controller.rb
class	ServicesController < ApplicationController

	def index
    @organs = Admin::Organ.where(active: true).order(name: :asc)
	end

	def show
		@service =  Service.where(id: params[:id]).first
    @service_units = @service.units.all

		set_meta_tags title:       @service.name,
                  description: @service.description,
                  keywords:    @service.get_keys,
                  author:      'Secretaria de Estado do Planejamento, Gestão e Patrimônio',
                  og: {
                    title:       @service.name,
                    description: @service.description,
                    type:        'website',
                    url:         @service.url,
                    image:       @service.organ.attachment
                  }
	end

end

app/views/admin/services/edit.html.erb
<h3>Serviços</h3>

<hr>
<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>
<div ng-controller="ServicesEditController" ng-init="loadService('<%= @service.id %>')">
	<%= render 'form' %>
	
</div>

	

<%= link_to 'Voltar', admin_services_path, class: 'btn btn-info' %>

app/views/admin/services/index.html.erb
<h3>Serviços</h3>
<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>


  Total de serviços cadastrados <span class="badge"><%= @services.length %></span>


<hr>
<a class="btn btn-primary" href="/admin/services/new">Adicionar novo</a>
  
<hr>

<div class="col-md-9">
  <table class="table table-hover table-fixed">

  <!--Table head-->
  <thead>
      <tr>
        <th>Órgão</th>
        <th>Nome</th>
        <!-- <th>Destaque</th> -->
        <th>Permalink</th>
        <th>Responsável pela informação</th>
        <th>Data da Criação</th>
        <th>Data da Modificação</th>
        <th>Quem atualizou?</th>
        <% if can_view Admin::ServicesController, 'edit' %>
          <th></th>
        <% end %>
        <% if can_view Admin::ServicesController, 'destroy' %>
          <th></th>
        <% end %>
      </tr>
    </thead>
  <!--Table head-->

  <!--Table body-->
  <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.organ.acronym if service.organ %></td>
          <td><%= service.name.truncate(25) %></td>
          <!-- <td><a style="text-decoration: none;"><%= service.highlights %><span class="badge"><%= service.highlights_value %></span></a><br></td> -->
          <td><%= service.permalink %></td>
          <td><%= service.coordinator %></td>
          <td><%= service.date %></td>
          <td><%= service.date_modified %></td>
          <td><%= service.latest_updater %></td>
          <td><span class="label label-<%= (service.active) ? 'success' : 'danger' %>">Ativo</td>
          <% if can_view Admin::ServicesController, 'edit' %>
            <td><a href="<%= edit_admin_service_path(service) %>">Editar</a></td>
          <% end %>
          <% if can_view Admin::ServicesController, 'destroy' %>
            <td><%= link_to 'Remover', [:admin, service], method: :delete, data: { confirm: 'Tem certeza?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  <!--Table body-->

</table>
<!--Table-->
</div>

app/views/admin/services/new.html.erb
<h3>Serviços</h3>

<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>
<hr>

<div ng-controller="ServicesNewController">
	<%= render 'form' %>
</div>
<%= link_to 'Voltar', admin_services_path, class: 'btn btn-info' %>