config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  get 'guia-de-servicos', to: 'services#index'
  get 'servico/:id/:permalink', to: 'services#show'
  get 'categoria/:category_slug/servicos', to: 'categories#index'
  get 'publico_alvo/:audience_slug/servicos', to: 'audiences#index'

  get 'orgaos', to: 'organs#index'
  get 'orgao/:permalink', to: 'organs#show'

  get 'unidades-de-atendimento', to: 'units#index'
  get 'unidade-de-atendimento/:permalink', to: 'units#show'

  get 'central-de-atendimento', to: 'centers#index'
  get 'central-de-atendimento/:permalink', to: 'centers#show'

  get 'categoria/:permalink', to: 'categories#index'
  get 'publico-alvo/:permalink', to: 'audiences#index'

  get 'arquivos', to: 'home#arquives'
  
  get 'api', to: 'home#api'

  get 'sobre', to: 'home#about'

  namespace :api do
    resources :services, :organs, :units, :centers, :categories, :audiences
    namespace :v1 do
      resources :services, :organs, :units, :centers, :categories, :audiences
    end
  end

  get 'admin', to: redirect('/admin/dashboard')

  namespace :admin do
    resources :services, :organs, :units, :centers, :categories, :audiences, :profiles, :users
    get 'dashboard', to: 'dashboard#index'
    get 'auth_generator', to: 'dashboard#auth_generator'
    post 'organs/uploader', to: 'organs#uploader'
  end

end

app/models/admin/profile.rb
class Admin::Profile
  include Mongoid::Document
  
  field :name, type: String

  has_and_belongs_to_many :auth_actions
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < AdminController
  before_action :set_admin_profile, only: [:show, :edit, :update, :destroy]

  before_action :verify_permission

  def index
    @admin_profiles = Admin::Profile.all
  end

  def new
    @admin_profile = Admin::Profile.new
    @controlers = AuthController.all
  end

  def edit
    @admin_profiles = Admin::Profile.page(params[:page])
    @controlers = AuthController.all
  end

  def show
    render json: @admin_profile
  end

  def create
    @admin_profile = Admin::Profile.new(admin_profile_params)

    respond_to do |format|
      if @admin_profile.save
        format.html { redirect_to admin_profiles_url, notice: 'Perfil criado com sucesso.' }
        format.json { render :show, status: :created, location: @admin_profile }
      else
        format.html { render :new }
        format.json { render json: @admin_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_profile.update(admin_profile_params)
        format.html { redirect_to admin_profiles_url, notice: 'Perfil atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @admin_profile }
      else
        format.html { render :edit }
        format.json { render json: @admin_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_profile.destroy

    respond_to do |format|
      format.html { redirect_to admin_profiles_url, notice: 'Perfil Alvo excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_admin_profile
      @admin_profile = Admin::Profile.find(params[:id])
    end

    def admin_profile_params
      params.require(:admin_profile).permit(:name, auth_action_ids: [])
    end
end

app/views/admin/profiles/_form.html.erb
<%= simple_form_for @admin_profile, html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, label: 'Nome', required: :true %>

  <div class="well">
    <div class="checkbox">
      <label>
        <input type="checkbox" id="checkAll">
        <i class="input-helper"></i>
        Marcar Todos
      </label>
    </div>

    <hr>
    
  	<ul style="list-style: none; padding: 0;">
  		<% @controlers.each do |controller| %>
  			<li>
          <div class="checkbox">
            <label>
              <input type="checkbox" class="checkAll">
              <i class="input-helper"></i>
              <%= controller.name %>
            </label>
          </div>
  				<ul style="list-style: none; padding: 10px 0 10px 30px;">
  					<% controller.auth_actions.each do |action| %>
  						<li>
						    <div class="checkbox">
						      <label>
                    <input type="checkbox" name="admin_profile[auth_action_ids][]" value="<%= action.id %>" <%= 'checked="checked"' if action.id.in? @admin_profile.auth_actions.collect(&:id) %>
						        <i class="input-helper"></i>
						        <%= action.description || action.name %>
						      </label>
						    </div>
  						</li>
  					<% end %>
  				</ul>
  			</li>
  		<% end %>
  	</ul>
  </div>

  <button class="btn btn-success pull-right">Salvar</button>
<% end %>

<script>
  $("#checkAll").click(function(){
    $(this).parent().parent().parent().find('ul li input:checkbox').not(this).prop('checked', this.checked);
  });
  $(".checkAll").click(function(){
    $(this).parent().parent().parent().find('ul li input:checkbox').not(this).prop('checked', this.checked);
  });
</script>

app/views/admin/profiles/edit.html.erb
<h1>Perfil</h1>

<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>
<hr>

<%= render 'form' %>

<%= link_to 'Voltar', admin_profiles_path, class: 'btn btn-info' %>

app/views/admin/profiles/index.html.erb
<h3>Perfil</h3>

<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>
<hr>

<a class="btn btn-primary" href="/admin/profiles/new">Adicionar novo</a>

<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @admin_profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>

        <td><a href="<%= edit_admin_profile_path profile %>">Editar</a></td>

        <td><%= link_to 'Remover', profile, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/profiles/new.html.erb
<h3 class="title">Perfil</h3>

<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>

<hr>

<%= render 'form' %>

<%= link_to 'Voltar', admin_profiles_path, class: 'btn btn-info' %>

app/views/admin/profiles/show.json.erb
json.extract! @admin_profile, :id, :name, :created_at, :updated_at