config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  get 'guia-de-servicos', to: 'services#index'
  get 'servico/:id/:permalink', to: 'services#show'
  get 'categoria/:category_slug/servicos', to: 'categories#index'
  get 'publico_alvo/:audience_slug/servicos', to: 'audiences#index'

  get 'orgaos', to: 'organs#index'
  get 'orgao/:permalink', to: 'organs#show'

  get 'unidades-de-atendimento', to: 'units#index'
  get 'unidade-de-atendimento/:permalink', to: 'units#show'

  get 'central-de-atendimento', to: 'centers#index'
  get 'central-de-atendimento/:permalink', to: 'centers#show'

  get 'categoria/:permalink', to: 'categories#index'
  get 'publico-alvo/:permalink', to: 'audiences#index'

  get 'arquivos', to: 'home#arquives'
  
  get 'api', to: 'home#api'

  get 'sobre', to: 'home#about'

  namespace :api do
    resources :services, :organs, :units, :centers, :categories, :audiences
    namespace :v1 do
      resources :services, :organs, :units, :centers, :categories, :audiences
    end
  end

  get 'admin', to: redirect('/admin/dashboard')

  namespace :admin do
    resources :services, :organs, :units, :centers, :categories, :audiences, :profiles, :users
    get 'dashboard', to: 'dashboard#index'
    get 'auth_generator', to: 'dashboard#auth_generator'
    post 'organs/uploader', to: 'organs#uploader'
  end

end

app/models/admin/audience.rb
class Admin::Audience
  include Mongoid::Document

	has_and_belongs_to_many :services

  field :name, type: String
  field :active, type: Mongoid::Boolean
  field :icon, type: String
  field :permalink, type: String

  before_save :touch_permalink

  def service_id
  	read_attribute(:service_id).to_s
  end

  def url
    "/publico-alvo/#{self.permalink}"
  end

  private
	  def touch_permalink
	    self.permalink = self.name.parameterize
	  end
end

app/controllers/admin/audiences_controller.rb
class Admin::AudiencesController < AdminController
  before_action :set_admin_audience, only: [:show, :edit, :update, :destroy]

  before_action :verify_permission, if: -> { request.path_parameters[:action] == 'index' && !request.format.json? }

  def index
    @admin_audiences = Admin::Audience.page(params[:page])
  end

  def new
    @admin_audience = Admin::Audience.new
  end

  def edit
    @audiences = Admin::Audience.page(params[:page])
  end

  def show
    render json: @admin_audience
  end

  def create
    @admin_audience = Admin::Audience.new(admin_audience_params)

    respond_to do |format|
      if @admin_audience.save
        format.html { redirect_to admin_audiences_url, notice: 'Público Alvo criado com sucesso.' }
        format.json { render :show, status: :created, location: @admin_audience }
      else
        format.html { render :new }
        format.json { render json: @admin_audience.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_audience.update(admin_audience_params)
        format.html { redirect_to admin_audiences_url, notice: 'Público Alvo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @admin_audience }
      else
        format.html { render :edit }
        format.json { render json: @admin_audience.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_audience.destroy
    respond_to do |format|
      format.html { redirect_to admin_audiences_url, notice: 'Público Alvo excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_admin_audience
      @admin_audience = Admin::Audience.find(params[:id])
    end

    def admin_audience_params
      params.require(:admin_audience).permit(:name, :active, :icon)
    end
end

app/controllers/api/audiences_controller.rb
class Api::AudiencesController < ApiController

	def index
		if params[:q]
			@audiences = Admin::Audience.full_text_search(params[:q], allow_empty_search: true)
		elsif params[:letter]
			@audiences =  Admin::Audience.where(name: /^#{params[:letter]}/i)
		else
			@audiences =  Admin::Audience.all
		end
	end

end

app/controllers/audiences_controller.rb
class AudiencesController < ApplicationController

	def index
		@audience = Admin::Audience.where(permalink: params[:permalink]).first
		@services = @audience.services.page(params[:page]).per(15)
	end

	def show
		@audiences = Admin::Audience.where(permalink: params[:permalink]).first
	end

end

app/views/admin/audiences/_form.html.erb
<%= simple_form_for @admin_audience, html: { class: 'form-horizontal' } do |f| %>

  <%= f.input  :name, label: 'Nome', :required => true %>
  <%= f.input :icon,label: 'Ícone', :collection => [['* asterísco','glyphicon glyphicon-asterisk'],['+ adição','glyphicon glyphicon-plus'],['- subtração','glyphicon glyphicon-minus'],['€ euro','glyphicon glyphicon-eur'],['☁ núvem','glyphicon glyphicon-cloud'],['✉ carta','glyphicon glyphicon-envelope'],['✏ caneta','glyphicon glyphicon-pencil'],[' taça','glyphicon glyphicon-glass'], [' música','glyphicon glyphicon-music'], [' busca','glyphicon glyphicon-search'], [' coração','glyphicon glyphicon-heart'],['Estrela','glyphicon glyphicon-star'], ['usuário','glyphicon glyphicon-user'],['filme','glyphicon glyphicon-film'],['engrenagem','glyphicon glyphicon-cog'],['lixeira','glyphicon glyphicon-trash'],['casa','glyphicon glyphicon-home'], ['documento','glyphicon glyphicon-file'], ['câmera','glyphicon glyphicon-camera'],['árvore','glyphicon glyphicon-leaf'], ['fogo','glyphicon glyphicon-fire'], ['avião','glyphicon glyphicon-plane'], ['carrinho de mercado','glyphicon glyphicon-shopping-cart'], ['hd','glyphicon glyphicon-hdd'], ['globo terrestre','glyphicon glyphicon-globe'], ['educação','glyphicon glyphicon-education'], ['empresa','glyphicon glyphicon-briefcase']] %>	
  <div class="col-sm-offset-3 col-sm-9">	
  	<%= f.input  :active, as: :boolean, label: 'Ativo' , :required => true%>

  </div>

  <hr>

  <button  class="btn btn-success pull-right">Salvar</button>
  
<% end %>

app/views/admin/audiences/edit.html.erb
<h1>Público alvo</h1>

<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>
<hr>

<%= render 'form' %>

<%= link_to 'Voltar', admin_audiences_path, class: 'btn btn-info' %>

app/views/admin/audiences/index.html.erb
<h3>Público alvo</h3>

<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>
<hr>

<a class="btn btn-primary" href="/admin/audiences/new">Adicionar novo</a>

<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @admin_audiences.each do |admin_audience| %>
      <tr>
        <td><%= admin_audience.name %></td>
        <td><span class="label label-<%= (admin_audience.active) ? 'success' : 'danger' %>">Ativo</td>
        <td><a href="<%= edit_admin_audience_path admin_audience %>">Editar</a></td>

        <td><%= link_to 'Remover', admin_audience, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/audiences/new.html.erb
<h3>Público alvo</h3>

<% if user_signed_in?%>
    <span style="color: blue;"><%= current_user.name %></span>,  <%= current_user.profile.name %> do sistema.<br><p class="">Lotado no orgão  <a href="/orgao/<%= current_user.organ.permalink %>"><%= current_user.organ.name %>.</p></a>
  <% end %>
<hr>

<%= render 'form' %>

<%= link_to 'Voltar', admin_audiences_path, class: 'btn btn-info' %>